### Eigen Value Decomposition for square matrix - Maths behind the concept 
#### Used - Google translator

In [18]:
import numpy as np

Square symmetric matrix - Eigen Value Decomposition

In [19]:
R = np.random.randn(10,5)

In [20]:
A = np.matmul(R,R.T)

In [21]:
A

array([[ 8.61414596,  2.22180254, -0.54449351,  4.62799097, -0.77122162,
        -0.37415501,  0.84452089,  3.75481421, -0.82951935, -1.00543637],
       [ 2.22180254,  1.21153226,  0.4704765 ,  1.17839886, -0.80645974,
        -0.11348459,  1.58049707,  0.48103364,  0.47383226, -1.54763512],
       [-0.54449351,  0.4704765 ,  3.04089585,  0.58540091, -1.0506982 ,
        -1.01159041,  0.12646968, -2.93443851,  1.02282421, -0.61628344],
       [ 4.62799097,  1.17839886,  0.58540091,  3.95662591, -2.41287456,
        -2.42955325, -1.62352133,  3.50800041, -1.93957893,  0.81531356],
       [-0.77122162, -0.80645974, -1.0506982 , -2.41287456,  3.80708581,
         3.28267827,  1.52903414, -2.76874116,  2.21332573, -0.55361373],
       [-0.37415501, -0.11348459, -1.01159041, -2.42955325,  3.28267827,
         3.47804723,  3.07111723, -2.83049245,  2.59880883, -1.96019902],
       [ 0.84452089,  1.58049707,  0.12646968, -1.62352133,  1.52903414,
         3.07111723,  5.86600975, -2.80181221

In [22]:
A.shape

(10, 10)

### Apply EVD

In [23]:
evd = np.linalg.svd(A)

type(evd) == tuple

#### A = Q.lambda.Q^T
Each matrix is 10X10 matrix

In [24]:
evd

(array([[-2.82172358e-01, -6.77503621e-01, -1.60910368e-02,
         -4.84427870e-01, -1.10515798e-01, -1.86718495e-01,
          1.18087635e-01, -2.36873519e-01, -3.22527672e-01,
         -7.26837695e-02],
        [-1.82778961e-02, -2.76001564e-01,  1.45992427e-01,
          1.39404509e-01, -2.38626666e-02,  6.98602885e-01,
         -5.56086892e-01, -4.10070035e-02, -1.32957966e-01,
         -2.55996494e-01],
        [ 8.08167425e-02,  1.59740977e-02,  6.23614184e-01,
         -1.08102833e-01,  3.52986235e-01, -9.31641350e-02,
          2.44201184e-01,  2.40400235e-01,  4.60257679e-03,
         -5.84727370e-01],
        [-3.38134498e-01, -2.52341214e-01,  2.57055475e-01,
         -1.89434318e-01,  1.06083981e-01,  7.74125600e-02,
         -1.18151535e-01,  4.27549661e-01,  5.60438488e-01,
          4.38097915e-01],
        [ 2.73725497e-01,  5.52442778e-05, -4.22478500e-01,
         -4.61502833e-01,  1.98675753e-01,  3.15223383e-02,
         -1.59196111e-01, -1.93638878e-01,  5.520851

In [25]:
evd[0].shape

(10, 10)

#### Calculating the L2 norm of the evd

In [26]:
np.linalg.norm(evd[0],ord=2,axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
evd[1]

array([2.20612213e+01, 1.28174608e+01, 6.93297061e+00, 4.08139652e+00,
       1.20100563e+00, 1.90578415e-15, 9.35756220e-16, 6.39946799e-16,
       4.21642550e-16, 3.07369574e-16])

This the eigen value of the matrix

In [28]:
q1_transpose = evd[2][0,:]

In [29]:
q1_transpose

array([-0.28217236, -0.0182779 ,  0.08081674, -0.3381345 ,  0.2737255 ,
        0.31381529,  0.3542169 , -0.5552756 ,  0.35240669, -0.26034906])

In [30]:
q1_transpose = q1_transpose.reshape(1,q1_transpose.shape[0])

In [31]:
q1_transpose

array([[-0.28217236, -0.0182779 ,  0.08081674, -0.3381345 ,  0.2737255 ,
         0.31381529,  0.3542169 , -0.5552756 ,  0.35240669, -0.26034906]])

### Dot product of q1_transpose with q1

In [32]:
np.matmul(q1_transpose,evd[0])

array([[ 1.00000000e+00, -1.48624353e-16,  9.38119531e-17,
         8.08355056e-18,  6.95098229e-17, -1.80164497e-17,
         6.70727310e-17,  1.08408496e-16,  8.58190379e-17,
        -1.85337108e-17]])

### Calcualting the rank of the matrix

In [34]:
np.linalg.matrix_rank(A)

5